### ISSUE TITLE
Fix comment

### ISSUE THREAD

**Issue by mjordan** [bondjimbond/islandora_video_embed#1]
@bondjimbond I don't think the comment in line 32 of your module file describes what https://github.com/bondjimbond/islandora_video_embed/blob/7.x/islandora_video_embed.module#L33-L36 does.

**Comment by bondjimbond** [comment]
Good catch, thanks. I copied another of my modules to build the skeleton for this one; guess I missed that comment!

**Comment by bondjimbond** [comment]
(Fixed with latest commit)
